name: learning_pose_detection
description: The easy way to use ML Kit for pose detection in Flutter.
version: 0.0.2


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  learning_input_image: ^0.0.6+2
  provider: ^6.0.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.salkuadrat.learning.learning_pose_detection
        pluginClass: LearningPoseDetectionPlugin
      ios:
        pluginClass: LearningPoseDetectionPlugin